### ISSUE TITLE
check out this!

### ISSUE THREAD

**Issue by TrueMyst** [AnveshakR/poster-generator#13]
Hey AnveshakR!

I like your project; by that, I mean the idea of generating music posters. I discovered your project when I was making mine, and I wasn't aware of this project till I researched things, and I should say I really do like it, though my original inspiration was from Pinterest. I feel like there is a lot of scope to this project, and I invite you to check out my version of generating music posters! It took me two months to finish this project. I intend to bring it to a website very soon 😊

Soo, maybe [check it out](https://github.com/TrueMyst/BeatPrints)? Feel free to leave any feedback :)
The only reason I'm sharing this with you is because our project is really similar.

Anyways, thanks!
Cheers
myst!

**Comment by AnveshakR** [comment]
Hey Myst,
That's really great to hear! We can talk more if you want, just mail me at rathoreanveshak@gmail.com.
