### ISSUE TITLE
cannot get flask secret for env file

### ISSUE THREAD

**Issue by greyXytOP** [AnveshakR/poster-generator#14]
i have no idea about what is flask as i am a beginner and need help in that.. please

**Comment by AnveshakR** [comment]
Hey, your flask secret code is just a alphanumeric code that Flask uses to securely sign your cookies. You are supposed to generate your own code and put it in the .env file. Here's a link to the [Flask documentation](https://flask.palletsprojects.com/en/3.0.x/config/#SECRET_KEY) for an explanation and example.

**Comment by greyXytOP** [comment]
Enter Spotify Album link: https://open.spotify.com/album/16PSZwABl4VFJvfDFOPOoB?si=5PFMQ6HCR7uySdOmDwrRSw
Enter height, width in pixels: 2480, 3508
Enter theme (light/dark): light
Traceback (most recent call last):
  File "e:\download software\poster-generator-main\poster-generator-main\poster_generator.py", line 254, in <module>
    poster, album_name = generator(album, resolution, theme)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\download software\poster-generator-main\poster-generator-main\poster_generator.py", line 75, in generator
    theme = options['theme']
            ~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

i am getting his eror i trried everything but cannot debug it.. help
