### ISSUE TITLE
got error in here

### ISSUE THREAD

**Issue by greyXytOP** [AnveshakR/poster-generator#15]
Enter Spotify Album link: https://open.spotify.com/album/16PSZwABl4VFJvfDFOPOoB?si=5PFMQ6HCR7uySdOmDwrRSw
Enter height, width in pixels: 2480, 3508
Enter theme (light/dark): light
Traceback (most recent call last):
File "e:\download software\poster-generator-main\poster-generator-main\poster_generator.py", line 254, in
poster, album_name = generator(album, resolution, theme)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "e:\download software\poster-generator-main\poster-generator-main\poster_generator.py", line 75, in generator
theme = options['theme']
~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

i am getting his error i tried everything but cannot debug it.. help

**Comment by AnveshakR** [comment]
Thanks for noticing that, I've pushed a commit that should fix this. [6a00ee2](https://github.com/AnveshakR/poster-generator/commit/6a00ee2d540ae4a032c02df8b846de4215f39c62)
